[kafka]
  brokers = ["kafka:9092"]
  user = ""
  password = ""
  group = "chetki"
  topic = "flows"

[elastic]
  address = "es01"
  port = "9200"
  index = "sflow"
  geoip = false
  ipdb = "/GeoLite2-City.mmdb"
  asndb = "/GeoLite2-ASN.mmdb"

[mac]
  "baa43ssc4ewe" = "phone"

[port]
  "443" = "https"
  "80" = "http"
  "53" = "dns"
  "993" = "imaps"

[protocol]
  "6" = "tcp"
  "17" = "udp"
  "58" = "ipv6-icmp"
  "0" = "ipv6-hop-by-hop"
  "1" = "icmp"
  "2" = "igmp"