[kafka]
  brokers = ["kafka:9092"]
  user = ""
  password = ""
  group = "chetki"
  topic = "flows"

[elastic]
  address = "es01"
  port = "9200"
  index = "sflow"
  geoip = false
  ipdb = "/GeoLite2-City.mmdb"
  asndb = "/GeoLite2-ASN.mmdb"

[mac]
  "baa43ssc4ewe" = "phone"